apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tripmind

resources:
  - base/configmap.yaml
  - base/secrets.yaml
  - base/postgres.yaml
  - base/api-service.yaml
  - base/ai-service.yaml
  - base/web-ui.yaml
  - base/ingress.yaml

commonLabels:
  app.kubernetes.io/name: tripmind
  app.kubernetes.io/managed-by: kustomize
