apiVersion: v1
kind: ConfigMap
metadata:
  name: travelrekha-config
data:
  # API Service
  jwt-expire: "7d"
  frontend-url: "https://travelrekha.com"
  google-callback-url: "https://api.travelrekha.com/api/v1/auth/google/callback"

  # AI Service
  default-ai-model: "gemini-2.0-flash"
  ai-execution-mode: "actual"
